# Generated by Django 3.2 on 2022-02-20 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('socies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('tipo_de_venta', models.CharField(choices=[('Humane', 'Hum'), ('General', 'Gen')], max_length=7, null=True)),
                ('forma_de_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Moneda Par', 'Moneda Par'), ('Tarjeta', 'tarjeta'), ('Debito', 'Debito'), ('Transferencia', 'Transferencia'), ('Humane', 'Humane'), ('Mercado Pago', 'MP')], max_length=15, null=True)),
                ('bonificacion', models.IntegerField(default=0)),
                ('monto_pago', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('cajere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajere', to=settings.AUTH_USER_MODEL)),
                ('socie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='socies', to='socies.socie')),
            ],
            options={
                'ordering': ['-creado_el'],
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salida', models.CharField(choices=[('Humane', 'Humane'), ('Pago Proveedores', 'Proveedor'), ('Diferencia de caja', 'Diferencia de caja'), ('Gasto Diario', 'Gasto Diario')], default='Proveedor', max_length=20)),
                ('remito_nro', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('humane', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='socies.socie')),
            ],
            options={
                'ordering': ['-creado_el'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('devolucion', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_elegido', to='producto.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='caja.venta')),
            ],
        ),
    ]
