# Generated by Django 3.2 on 2022-02-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('emprendimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('dni', models.CharField(blank=True, max_length=9, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono', models.CharField(blank=True, default='+54 ', max_length=17, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('proveedor', models.BooleanField(blank=True, default=False, null=True)),
                ('humane', models.BooleanField(blank=True, default=True, null=True)),
                ('tiendas', models.ManyToManyField(related_name='tienda', to='socies.Tienda')),
            ],
            options={
                'ordering': ('codigo',),
            },
        ),
    ]
