# Generated by Django 3.2 on 2022-03-10 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='socie',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='socie',
            name='humane',
        ),
        migrations.RemoveField(
            model_name='socie',
            name='tiendas',
        ),
        migrations.AddField(
            model_name='socie',
            name='adherente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socie',
            name='fecha_de_egreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socie',
            name='fecha_de_ingreso',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socie',
            name='modo_de_egreso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='socie',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='socie',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='socie',
            name='telefono',
            field=models.CharField(blank=True, default='+54 9 ', max_length=17, null=True),
        ),
    ]
